### ISSUE TITLE
Image should be full width on front page

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/thecookingproject#9]
The Cooking Project team requested that the image on the [front page](thecookingproject.org) be full width.

**Comment by ChrisHardie** [comment]
Looks like this is was done elsewhere:

![screen shot 2018-03-19 at 16 09 37](https://user-images.githubusercontent.com/311772/37619460-f647abe4-2b8f-11e8-9aff-ee991af5e775.png)

Closing.
